<?php
    $lang['number']   = 'Ref';
    $lang['date']     = 'Date';
    $lang['time']     = 'Billing time';
    $lang['due']      = 'Due';
    $lang['to']       = 'Billing to';
    $lang['from']     = 'Billing from';
    $lang['product']  = 'Product';
    $lang['qty']      = 'Qty';
    $lang['price']    = 'Net U Price';
    $lang['discount'] = 'Net discount';
    $lang['vat_rate'] = 'Vat rate';
    $lang['vat']      = 'Vat';
    $lang['totalWoVat'] = 'Total net';
    $lang['total']    = 'Total';
    $lang['page']     = 'Page';
    $lang['page_of']  = 'of';
