<?php
    $lang['number']   = 'N°';
    $lang['date']     = 'Date facture';
    $lang['time']     = 'Heure de facturation';
    $lang['due']      = 'Date d\'échéance';
    $lang['to']       = 'Facturé à';
    $lang['from']     = 'Facturé par';
    $lang['product']  = 'Produit';
    $lang['qty']      = 'Qté';
    $lang['price']    = 'Prix unit. HT';
    $lang['discount'] = 'Remise';
    $lang['vat']      = 'TVA';
    $lang['totalWoVat'] = 'Total HT';
    $lang['total']    = 'Total TTC';
    $lang['page']     = 'Page';
    $lang['page_of']  = 'sur';
